# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EndScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class EndScreenView(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(815, 330)
        Form.setStyleSheet("")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, -10, 471, 141))
        font = QtGui.QFont()
        font.setPointSize(76)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(100, 110, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.Notif = QtWidgets.QLabel(Form)
        self.Notif.setGeometry(QtCore.QRect(500, 30, 291, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Notif.setFont(font)
        self.Notif.setObjectName("Notif")
        self.Comment = QtWidgets.QLabel(Form)
        self.Comment.setGeometry(QtCore.QRect(530, 90, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Comment.setFont(font)
        self.Comment.setObjectName("Comment")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(480, 150, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.ps2 = QtWidgets.QLabel(Form)
        self.ps2.setGeometry(QtCore.QRect(480, 190, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.ps2.setFont(font)
        self.ps2.setObjectName("ps2")
        self.ps1 = QtWidgets.QLabel(Form)
        self.ps1.setGeometry(QtCore.QRect(480, 230, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.ps1.setFont(font)
        self.ps1.setObjectName("ps1")
        self.Replay = QtWidgets.QPushButton(Form)
        self.Replay.setGeometry(QtCore.QRect(80, 200, 121, 41))
        self.Replay.setObjectName("Replay")
        self.Leave = QtWidgets.QPushButton(Form)
        self.Leave.setGeometry(QtCore.QRect(210, 250, 121, 41))
        self.Leave.setObjectName("Leave")
        self.Change = QtWidgets.QPushButton(Form)
        self.Change.setGeometry(QtCore.QRect(210, 200, 121, 41))
        self.Change.setObjectName("Change")
        self.Settings = QtWidgets.QPushButton(Form)
        self.Settings.setGeometry(QtCore.QRect(80, 250, 121, 41))
        self.Settings.setObjectName("Settings")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Morpion by PetchouDev"))
        self.label.setText(_translate("Form", "Morpion"))
        self.label_2.setText(_translate("Form", "By PetchouDev"))
        self.Notif.setText(_translate("Form", "Congratulations {}"))
        self.Comment.setText(_translate("Form", "You won the game !"))
        self.label_3.setText(_translate("Form", "Stats :"))
        self.ps2.setText(_translate("Form", "Player1"))
        self.ps1.setText(_translate("Form", "Player2"))
        self.Replay.setText(_translate("Form", "Replay"))
        self.Leave.setText(_translate("Form", "Leave"))
        self.Change.setText(_translate("Form", "Change Players"))
        self.Settings.setText(_translate("Form", "Settings"))
