# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mode.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class ModeSelectorView(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(411, 142)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 10, 411, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.local = QtWidgets.QPushButton(Form)
        self.local.setGeometry(QtCore.QRect(10, 90, 131, 41))
        self.local.setObjectName("local")
        self.create = QtWidgets.QPushButton(Form)
        self.create.setGeometry(QtCore.QRect(140, 90, 131, 41))
        self.create.setObjectName("create")
        self.join = QtWidgets.QPushButton(Form)
        self.join.setGeometry(QtCore.QRect(270, 90, 131, 41))
        self.join.setObjectName("join")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Mode Selection"))
        self.local.setText(_translate("Form", "Local"))
        self.create.setText(_translate("Form", "Create online game"))
        self.join.setText(_translate("Form", "Join online game"))
