# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\mathe\Documents\code\Games\Morpion\GUI\ui\Settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(229, 193)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 10, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(60, 70, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.eraseDatas = QtWidgets.QPushButton(Dialog)
        self.eraseDatas.setGeometry(QtCore.QRect(30, 100, 171, 41))
        self.eraseDatas.setObjectName("eraseDatas")
        self.btn = QtWidgets.QPushButton(Dialog)
        self.btn.setGeometry(QtCore.QRect(150, 40, 71, 31))
        self.btn.setObjectName("btn")
        self.Save = QtWidgets.QPushButton(Dialog)
        self.Save.setGeometry(QtCore.QRect(10, 160, 93, 28))
        self.Save.setObjectName("Save")
        self.Cancel = QtWidgets.QPushButton(Dialog)
        self.Cancel.setGeometry(QtCore.QRect(120, 160, 93, 28))
        self.Cancel.setObjectName("Cancel")
        self.le = QtWidgets.QLabel(Dialog)
        self.le.setGeometry(QtCore.QRect(10, 45, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(True)
        self.le.setFont(font)
        self.le.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.le.setFrameShadow(QtWidgets.QFrame.Plain)
        self.le.setLineWidth(1)
        self.le.setMidLineWidth(12)
        self.le.setObjectName("le")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Language Settings"))
        self.label_3.setText(_translate("Dialog", "Other settings"))
        self.eraseDatas.setText(_translate("Dialog", "Erase datas"))
        self.btn.setText(_translate("Dialog", "Change"))
        self.Save.setText(_translate("Dialog", "Save"))
        self.Cancel.setText(_translate("Dialog", "Cancel"))
        self.le.setText(_translate("Dialog", "TextLabel"))
